DATASET:
  TRAIN_FILE : "/home/mihnea/data/VQA_DL/miniCOCO/miniCOCOtrain.json"
  TRAIN_IMG_FOLDER : "/home/mihnea/data/VQA_DL/miniCOCO/miniCOCO_train2014"
  VAL_FILE : "/home/mihnea/data/VQA_DL/miniCOCO/miniCOCOval.json"
  VAL_IMG_FOLDER : "/home/mihnea/data/VQA_DL/miniCOCO/miniCOCO_val2014"
  TRAIN_VAL_IMG_EMBEDDINGS_FOLDER : "/home/mihnea/data/VQA_DL/img_embeddings"