DATASET:
  TRAIN_FILE : "/home/diana/data/VQA_DL/miniCOCO/miniCOCOtrain.json"
  TRAIN_IMG_FOLDER : "/home/diana/data/VQA_DL/miniCOCO/miniCOCO_train2014"
  VAL_FILE : "/home/diana/data/VQA_DL/miniCOCO/miniCOCOval.json"
  VAL_IMG_FOLDER : "/home/diana/data/VQA_DL/miniCOCO/miniCOCO_val2014"
  TRAIN_VAL_IMG_EMBEDDINGS_FOLDER : "/home/diana/data/VQA_DL/img_embeddings"
  LABELS: '/home/diana/VQA/configs/labels.yaml'
  WORD_VOCABULARY: /home/diana/VQA/configs/word_vocabulary.yaml
  WORD_VOCABULARY_SIZE: 4479